# Generated by Django 4.1.12 on 2023-10-16 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cartitem_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='category',
        ),
    ]
